spring.application.name=intern
# MySQL Connection


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

file.upload-dir=D:/uploads/notes/
file.result-dir=D:/uploads/results/
# Set the maximum allowed size for a single file
spring.servlet.multipart.max-file-size=10MB

# Set the maximum allowed size for the entire multipart request
spring.servlet.multipart.max-request-size=10MB
# Give Spring Boot a permanent place to put uploaded files temporarily
spring.servlet.multipart.location=/tmp/tomcat-uploads

# Development Credentials
spring.security.user.name=admin
spring.security.user.password=admin123